apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: example-private-helm-oci
  namespace: argocd
stringData:
  name: my-oci-charts
  url: ghcr.io/morey-tech/example-private-helm-oci
  type: helm
  enableOCI: "true"
  username: token-name
  password: token-password