name: Release

on:
  release:
    types: 
    - created

jobs:
  publish-charts:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.10.0'
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
   
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Publish chart
      env:
        HELM_EXPERIMENTAL_OCI: '1'
        CHARTS_REPO: ghcr.io/morey-tech/example-private-helm-oci
        VERSION: ${{ github.ref_name }}
      run: |
        CHART_VERSION=$(echo $VERSION | cut -c 2-)
        cd charts/guestbook
        helm dep up
        helm package . --version ${CHART_VERSION} --app-version ${VERSION}
        helm push guestbook-${CHART_VERSION}.tgz oci://${CHARTS_REPO}